### ISSUE TITLE
No icons - double tap on iOS devices 

### ISSUE THREAD

**Issue by ludovicbret** [Urigo/Ionic-MeteorCLI-WhatsApp#12]
Hi,

I tried to fix this but can't get my head throw it.
Icons (ionic fonts) works well in browser but don't show up on iOS device or simulator. There's also an issue with tap actions on those, only the double tap works. I think it is related to the way ionic is included.
Could you provide some help here ?

Thx

**Comment by buymybm100** [comment]
Am getting the same issue on Android - no icons displayed when running in Emulator. 
Using chrome://inspect, I see this error : 

Failed to load resource: the server responded with a status of 404 (Not Found) http://localhost:12592/packages/dab0mb_ionic-assets/.npm/package/node_modules/ionic-sdk/release/fonts/ionicons.ttf?v=2.0.1

**Comment by DAB0mB** [comment]
Thank you for bringing this issue into my attention.
I'm really busy these days with other projects, and I have little time to check on this, but eventually I should come back to this project and I will fix it and update it. If you manage to find a solution do tell so we can all share it :-)

**Comment by juancho559** [comment]
Hi,

I was trying to solve this issue by using this patch (https://gist.github.com/IgorMinar/863acd413e3925bf282c), But It didn't work in my project. 

Any ideas?

Thanks!!

**Comment by Furqankhanzada** [comment]
@ludovicbret i have same issue. have you find any solution ?

**Comment by DAB0mB** [comment]
It's probably an issue with the way the assets are being loaded, I'm working on a fix and hopefully it will be ready soon.

See also [issue in meteor-npm-ionic](https://github.com/DAB0mB/meteor-npm-ionic/issues/1).

**Comment by juancho559** [comment]
I found something very interesting. When you make a request by clicking a button and you try to update **window.location.href**, magically everything starts working. So I just solved my problem by making an automatic request the first time that I access my mobile app. I know that It's not the cleanest way but it works. I think that this problem is related to the new changes in IOS9 for  UIWebView class. The patch that I mentioned before seems to solve the problem but in my case it didn't work.

**Comment by dvmorris** [comment]
Just to add to this, the font files are not actually making it into the apk or ipa bundles:

    /path/to/***.xcarchive/Products/Applications/***.app/www/application/packages/dab0mb_ionic-assets/

is empty after running a meteor build or meteor run, when it should have this folder structure:

    dab0mb_ionic-assets/.npm/package/node_modules/ionic-sdk/release/fonts/

**Comment by dvmorris** [comment]
@juancho559 could you share your fix with me? Where did you put that code, and what exactly does it look like?

**Comment by martinothamar** [comment]
In regards to the ionicons, I solved it by just installing [meteoric-ionicons-sass](https://atmospherejs.com/meteoric/ionicons-sass).

I can't seem to get my head around the double-tap stuff though. Did you have a fix for that @juancho559? For now I'm just using `on-release` instead, but buttons for plugins and the likes are still broken, because they use `ng-click`.

**Comment by juancho559** [comment]
Hi @martinothamar and @dvmorris 
I'm going to make the fix that it worked for me in the angular-meteor-whatsapp tutorial and I will share the solution with you as soon as possible.  As I said in the post before, it's not the cleanest solution but in the meantime, it seems to work.

**Comment by tomitbe** [comment]
The double tap can be solved by replacing ng-click or the href to on-release. Not a perfect solution, but for now the only option it seems.

**Comment by dvmorris** [comment]
Thanks, guys. I will try these out this weekend and report back.

**Comment by juancho559** [comment]
Hi guys,
These are the things that I did:

**client/scripts/controllers/default.controller.js:** This controller is going to do an automatic request by changing windows.location.href in order to fix the problem that we have in IOS 9.
**client/templates/default.html:** Html page connected with default.controller.   
**app.js:** I added a global variable with a defaulturl. This url should be changed with the ip of the server where is running meteor. In Debug time can be localhost.
Also, I add a new cotroller **DefaultCtrl**.
**routes.js:** I added a new state and I changed the default page in order to ensure that always when a user enters to the application, the system is going to run the code that fixes the problem in IOS9.
**tabs.html:** I just changed the unusable tabs with the default home page. 
**login.js:** Finally, I just implemented a code in order to redirect logged users. I implemented this code to ensure the same functionality that we had in this sample application. 

As I said before, it's not the cleanest solution but it works for me. Let me know if you have a better solution. 

https://github.com/juancho559/whatsapp

Regards!!

**Comment by dvmorris** [comment]
@martinothamar Regarding your fix for the ionic icons, what else did you do besides add that meteor package to your project? Did you have to include an @import statement in a .scss file somewhere? If so, did you put it in an existing file or did you create a new file? 

The instructions for that package say to include an @import line in "your app's .scss file", but this tutorial app does not have a main .scss file.

**Comment by martinothamar** [comment]
I'm only using parts of the tutorial for starting a new unrelated project. You just  create a .scss file. I have it under `/client/styles.main.scss`. Add the import at the top of it.

**Comment by martinothamar** [comment]
There might be issues related to the ionic packages referenced in the tutorial.

I've commented a fix on a [similar issue](https://github.com/Urigo/angular-meteor/issues/1351#issuecomment-217875507) on the angular-meteor repo. Basically just using the official ionic-package fixed it for me.

**Comment by vivekmago** [comment]
Any update on the issue would be great?

**Comment by pezaohe** [comment]
Hi guys!!! @DAB0mB is there some solution?

**Comment by mncvnn** [comment]
Hi @juancho559 ,
Your solution is perfect for me, however, it seem like the keyboard not show up. Will it show up in actual device? I mean I run on an simulation (iPhone 6s plus) so I did not know what the real device would do.
I looking around and it seem like your solution is the only one that work for now. And not official solution has been made.
Thanks.

**Comment by mncvnn** [comment]
Hi @juancho559 ,
Hi all,
Just try to test @juancho559 solution on my device. And this is my result:
ANDROID (real device):

1. The keyboard did show up.
2. The icon not work.

iOS (simulation):

1. The keyboard seem show it (just a ![image](https://cloud.githubusercontent.com/assets/19810923/15984093/9f344a0a-2fe8-11e6-85cf-ed87c7ddf3ab.png) Done part), I believe that it would work on the real device.
3. The icon did show up.

I attach some screenshot here:
Android:
![screenshot jun 11 2016 15 00 26](https://cloud.githubusercontent.com/assets/19810923/15984108/28036d48-2fe9-11e6-80f6-77253279f480.png)

iOS:
![simulator screen shot jun 11 2016 3 05 58 pm](https://cloud.githubusercontent.com/assets/19810923/15984110/37ddb214-2fe9-11e6-8734-6a4f197f4ced.png)
Chat and Keyboard:
![simulator screen shot jun 11 2016 3 24 12 pm](https://cloud.githubusercontent.com/assets/19810923/15984111/4328fe1c-2fe9-11e6-9f33-ac1315efe1ff.png)

<pre></pre>
I'll try to find the problem of android, because I have another meteor-angular-ionic and It works fine on my real device and iOS simulation:

![screenshot_2016-06-11-15-16-05](https://cloud.githubusercontent.com/assets/19810923/15984117/8bf8bd3a-2fe9-11e6-8c00-274b1ccce985.png)

**Comment by ntoka** [comment]
Any updates on the double-tap fix?

Missing icons can be fixed through solution found here:
http://stackoverflow.com/questions/36762888/ionic-icons-are-not-shown-in-android-simulator

**Comment by jvillamor-visp-net** [comment]
Hi. Any updates on the fix?

**Comment by jgontrum** [comment]
Some update on this would be nice. Im really starting to lose faith in Angular-Meteor-Ionic, when a grave bug like this remains unfixed for months. There can't be too many people actually using it...

**Comment by DriesVandermeulen** [comment]
[Solution](https://github.com/Urigo/angular-meteor/issues/1341#issuecomment-248269031) 
@DAB0mB This should be included in the documentation.

**Comment by DAB0mB** [comment]
@DriesVandermeulen Thanks for the solution! This issue has been around for a while now.. Hopefully it will be deployed today!
